# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# Testing y

name: AUTO_VISITOR_EA
 
on: 
  push: 
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/30 * * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: 💿 install module
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: 🚀 Run auto visitor
      run: |
        python visit.py

    - name: ➕ Proses Commit
      run: |
        git config --global user.name "garz"
        git config --global user.email "g4rzkurniawan@gmail.com"
        rm -rf .git
        git init
        git add .
        git commit -m "`env TZ=Asia/Jakarta date`"
        git remote add origin git@github.com:garz-id/auto_visitor.git
        
    - name: ✅ Proses Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        force: true
